### PR TITLE
fix yoenkins build logs with --follow

### LINKED ISSUE #148: [Feature-Request]: Simple way to replay a job with the same parameter as the last time it was run
### Describe the feature you would like to see

it would be great if we had something like

yojenkins build rebuild URL

it should trigger a new build from the job of URL using the parameters from the last build (have it failed or not)
also, it should show the output (with --follow) on the console.

that would be the ultimate tool to test jenkinsfiles!

### Describe alternatives/workarounds you have considered

writing a PR

### Which operating systems are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Other
- [ ] I don't know

### How is your day going?

Not bad

### PR DESCRIPTION
**Pull request by marcosdiez**
Hi Ismet!
This is Marcos from the DevOps days in Florida! 
I hope you liked the book I recommended, also that the next hurricane does not hit your house!

closes #148 

## Change Motivation

`yojenkins build logs XXXXX --latest --follow` was not working as expected. I fixed it. The issue was with the `--follow` part.

---------------------------------------------
## Describe the Changes Made

We can now use `--follow` with:

- a job that is already done. it will successfully exit after displaying the output.
- a job that is running. it will successfully exit after the job is done.

---------------------------------------------
## Change Type
*(Check any that apply)*

- [X] Bug Fix
- [ ] New Feature
- [ ] Code Refactoring
- [ ] Documentation
- [ ] Formatting
- [ ] Automation
- [ ] Unit Tests
- [ ] Other

---------------------------------------------
## How Has This Been Tested?
*(Please describe the tests/commands that you ran to verify your changes)*

I test with 3 jobs:

- one that was done
- one that was running and ended
- one that runs (almost) forever so we can see if it works overnight

---------------------------------------------
# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (if applicable)
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by ismet55555** [comment]
In addition, do you have some screenshot or something showing where it wasn't working or erroring out before, or missing logs.  I see you reference those two bullets, and I tried to recreate but wasn't able to.

**Comment by ismet55555** [comment]
Ok I like that suggestion actually, I do think the `progressiveText` is the way to go. So if you want you can comment out the old stuff, keep your stuff, and I can try to do the switch over when it doesn't work. Or if you want to do it, it's cool with me.

**Comment by ismet55555** [comment]
Yeah no problem. Can you please redirect your PR to branch `build-logs-follow-work` in the main repo? I'll work from there and we can merge it all after

**Comment by marcosdiez** [comment]
Sure! Done!

**Review by ismet55555 — APPROVED** [review]
LGTM. Thank you for the contribution!

**Pull request merged**
